export const People = [
  "Ada Ng",
  "Andy Chan",
  "Andy Fong",
  "Angela Ng",
  "Anne Lam",
  "Ashley Chan",
  "Brenda Li",
  "Carmen Lung",
  "Carol Chiu ",
  "Chris Yeung",
  "Christine Ng",
  "Cindy Ching",
  "Clive Wan",
  "Daniel Chan",
  "Dennis Yuen",
  "Edith Suen",
  "Emily Leung",
  "Eric Tang",
  "Eva Oegger",
  "Florence Chan ",
  "George Wong",
  "Helen Man",
  "Helen Yip",
  "Irene Wong",
  "Ivy Lee",
  "Jeff Lai",
  "Jobbie Leung",
  "Johnny Chan ",
  "Kathy Lo ",
  "Kelly Lu ",
  "Kelvin Chen",
  "Kelvin Chow",
  "Kenneth Ng",
  "Kennex Tse",
  "Kevin Chan ",
  "Kurt Yu ",
  "Martin Kow",
  "Minna Poon ",
  "Peter Schulz",
  "Phenix Pun",
  "Phiona Fong",
  "Ronald Lee",
  "Roy Hung",
  "Samuel Tang ",
  "Sanford Ho ",
  "Stanley Chan ",
  "Stanley Chiu",
  "Stanley Hung ",
  "Thomas Lai",
  "Timothy Sit",
  "Vicky Fung",
  "Vienna Tam",
  "Wayne Chan",
  "Will Chan",
  "William On"
];
